global:
  smtp_smarthost: 'sandbox.smtp.mailtrap.io:2525'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: '0fa5e170a36ac5'
  smtp_auth_password: '3f9ee193bc894d'
  resolve_timeout: 60s

route:
  receiver: 'default-receiver'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 2m
  routes:
    - match:
        severity: critical
      receiver: 'critical-receiver'
    - match:
        severity: warning
      receiver: 'telegram'

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'default-team@example.com'
        send_resolved: true

  - name: 'critical-receiver'
    email_configs:
      - to: 'critical-team@example.com'
        send_resolved: true

  - name: 'warning-receiver'
    email_configs:
      - to: 'warning-team@example.com'
        send_resolved: true

  - name: 'telegram'
    telegram_configs:
      api_url: 'https://api.telegram.org/bot<TELEGRAM_BOT_TOKEN>/sendMessage'
      chat_id: '<TELEGRAM_USER_ID>'
      send_resolved: true


inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
