version: '2'

services:
  prometheus:
    container_name: prometheus
    networks:
      - metrics
    image: prom/prometheus:latest
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./alert-rules:/etc/prometheus/alert-rules"
    ports:
      - "9091:9090"


  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.23.0
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager.yml:/config/alertmanager.yml"
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug
    networks:
      - metrics

networks:
  metrics:
    external: true

volumes:
  alertmanager-data:
