global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
rule_files:
  - './alert-rules/*.yml'
scrape_configs:
  - job_name: aggregated-trace-metrics
    static_configs:
      - targets: ['otel:8889']

  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: alertmanager
    static_configs:
      - targets: ['alertmanager:9093']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            # Alertmanager's default port is 9093
            - alertmanager:9093


